### ISSUE TITLE
'10100110110001000000' is not a valid integer value for Int64 type.  (Number Base entering into Binary)

### ISSUE THREAD

**Issue by gorhinstroebel** [shaunroselt/Roselt-Developer-Tools#1]
When using Number Base tool, and entering number lonnger or equal to or greater than '10100110110001000000'  in the binary textbox it
Completly crashes on 64bit MacOS release
 and ARM64 MacOS release
 (on arm sometimes gives a show message error and does not crash the entire application but 99%
 of the time it crashes entire application). With Windows you at least  get a Error that pops up but does not crash the entire software 

![Screenshot 2023-01-27 at 22 49 38](https://user-images.githubusercontent.com/102311306/215194888-00521ed1-332d-446f-a493-9195ae8adc33.png)

**Comment by shaunroselt** [comment]
Thanks. I found the issue and fixed it.

**Comment by gorhinstroebel** [comment]
Nice!


> Thanks. I found the issue and fixed it.
