### ISSUE TITLE
Copy to Clipboard buttons not working on Number Base Converter

### ISSUE THREAD

**Issue by shaunroselt** [shaunroselt/Roselt-Developer-Tools#21]
Whenever I click on the "Copy to Clipboard" button on the Number Base Converter tool, then I get an exception (access violation):

![exception (access violation) with Number Base Converter Tool on Roselt Developer Tools](https://github.com/shaunroselt/Roselt-Developer-Tools/assets/5418178/2b44356e-a11c-4647-be97-5958f3a288bf)

**Comment by teorey** [comment]
Hi Shaun.

What a great idea to make some programming support tools, also multiplatform.

I have a posible solution to this bug:

procedure TFrame_NumberBaseConverter.CopyOutputToClipboard(Sender: TObject);
var
  ClipboardService: IFMXClipboardService;
  EditText:string;
  EditButton:TEditButton;
  Ctrl:TControl;
  Edit:TEdit;
begin
  //ADD TEO 20230613 23:27:04 CEST - FIX BUG - TESTED ONLY WIN 11 64 BITS OK

      // --> ORIGINAL COMMENTED
  //if TPlatformServices.Current.SupportsPlatformService(IFMXClipboardService, ClipboardService) then
  //  ClipboardService.SetClipboard(TEdit(TControl(Sender).ParentControl).Text);

      // --> MODIFIED ADDED
  if TPlatformServices.Current.SupportsPlatformService(IFMXClipboardService, ClipboardService) then
  begin
    if Sender is TEditButton then
    begin
      EditButton := TEditButton(Sender);
      if (EditButton.Parent.Parent is TEdit) then
      begin
        Edit:= TEdit(EditButton.Parent.Parent);
        ClipboardService.SetClipboard(Edit.Text);
      end;
    end;
  end;
  //END ADD TEO 20230613 23:27:04 CEST FIX BUG

end;

**Comment by shaunroselt** [comment]
Fixed this in the following commit: https://github.com/shaunroselt/Roselt-Developer-Tools/commit/af50b0ccc6e95e160936a3afb61b231b6a7b0909

Thanks @teorey

**Comment by teorey** [comment]
Your welcomme.
