### ISSUE TITLE
"All Tools" Searchbox doesn't work

### ISSUE THREAD

**Issue by shaunroselt** [shaunroselt/Roselt-Developer-Tools#4]
I get an access violation every time I try to search for something:

![image](https://user-images.githubusercontent.com/5418178/215258018-877cd59c-7b27-4ec8-94f3-c3b884d7af84.png)

I think all the search code will need to be rewritten as it was originally written before the tools were created dynamically. So it's quite old code.

**Comment by gorhinstroebel** [comment]
I don't seem to be getting that error. Search works perfectly on my end?

**Comment by shaunroselt** [comment]
> Works on Debug but not on release.

Thanks. That's useful to know.

I tested it on my side. It also works in Debug Mode, but not in Release Mode.

I'm not sure why yet though.
