### ISSUE TITLE
Heading does not change when selecting a tool

### ISSUE THREAD

**Issue by gorhinstroebel** [shaunroselt/Roselt-Developer-Tools#8]
Bug: When choosing a tool from the sidebar The Title of the Text Does change to that of the selected tool,  
when selecting a tool from the All Tools Home menu  or Searching for a tool then selecting a tool has been selected the title still remains "All Tools"

![Screenshot 2023-01-29 at 05 10 27](https://user-images.githubusercontent.com/102311306/215302432-d9214353-e7ed-4419-a162-ccd44ae5982e.png)
![Screenshot 2023-01-29 at 05 09 23](https://user-images.githubusercontent.com/102311306/215302404-6bdc6272-9786-4c54-8547-83a4a4700549.png)

**Comment by shaunroselt** [comment]
I fixed this in the latest PR. Thanks @gorhinstroebel
