### ISSUE TITLE
Integer overflow when scaling down Application window. 

### ISSUE THREAD

**Issue by gorhinstroebel** [shaunroselt/Roselt-Developer-Tools#9]
When resizing the Application window to the point that it only shows the left navigation of all the tools, an integer overflow takes place.
 Application can't then be found in task manager, requires complete reboot to close the application.

<img width="321" alt="Screenshot 2023-01-29 140013" src="https://user-images.githubusercontent.com/102311306/215324903-3b90180e-5e12-45a9-9de4-1772499b8c09.png">

**Comment by shaunroselt** [comment]
What operating system was this on? Windows or MacOS?


Were you running a debug build or release build?

**Comment by shaunroselt** [comment]
I tested this on my side on Windows 11 with 64bit. It seems to be working without any errors. I do not get the same integer overflow error.

I tested both with Delphi 11.3 using debug and release builds.


@gorhinstroebel Can you please confirm if you still have this issue or not? If you have it, then please provide some additional info regarding how to reproduce it.

**Comment by gorhinstroebel** [comment]
@shaunroselt this appears on macos Arm 
All i done was resize the window like in the picture

![image](https://github.com/shaunroselt/Roselt-Developer-Tools/assets/102311306/d5b51717-5f1a-465c-8379-9b57671a12fb)

**Comment by gorhinstroebel** [comment]
Issue resolved in PR: https://github.com/shaunroselt/Roselt-Developer-Tools/pull/38
